# Generated by Django 5.1.7 on 2025-08-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='machine_age',
        ),
    ]
